apiVersion: v1
kind: Namespace
metadata:
  name: keda-demo
spec: {}
status: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
 name: my-keda-serviceaccount
 namespace: keda-demo
 annotations:
   eks.amazonaws.com/role-arn:  arn:aws:iam::458419607076:role/IRSA-KEDA-Demo