apiVersion: v1
kind: Namespace
metadata:
  name: keda-demo
spec: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-app-keda
  name: my-app-keda
  namespace: keda-demo
spec:
  selector:
    matchLabels:
      app: my-app-keda
  template:
    metadata:
      labels:
        app: my-app-keda
    spec:
      containers:
      - image: vinod827/keda-demo:1.0.0
        name: my-app-keda
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m" # request 100 milliCPU (0.1 CPU)
            memory: "128Mi" # request 128 Mebibytes of memory
          limits:
            cpu: "200m" # limit to 200 milliCPU (0.2 CPU)
            memory: "256Mi" # limit to 256 Mebibytes of memory
---
apiVersion: v1
kind: Secret
metadata:
  name: test-secrets
  namespace: keda-demo
data:
  AWS_ACCESS_KEY_ID: <> # Required 
  AWS_SECRET_ACCESS_KEY: <> # Required.
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-aws
  namespace: keda-demo
spec:
  secretTargetRef:
  - parameter: awsAccessKeyID     # Required.
    name: test-secrets            # Required.
    key: AWS_ACCESS_KEY_ID        # Required.
  - parameter: awsSecretAccessKey # Required.
    name: test-secrets            # Required.
    key: AWS_SECRET_ACCESS_KEY    # Required.
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: my-app-scaledobject
  namespace: keda-demo
  #annotations:
    #autoscaling.keda.sh/paused-replicas: "0"                # Optional. Use to pause autoscaling of objects
    #autoscaling.keda.sh/paused: "true"                      # Optional. Use to pause autoscaling of objects explicitly
spec:
  scaleTargetRef:
    name: my-app-keda
    kind: Deployment
  pollingInterval: 5  # Optional: Set the polling interval for the scaler in seconds
  cooldownPeriod: 20   # Optional: Set the cooldown period for the scaler in seconds
  minReplicaCount: 0   # Set the minimum number of replicas
  maxReplicaCount: 10  # Set the maximum number of replicas
  #fallback: # Optional: Fallback strategy when metrics are unavailable for the apps
    #failureThreshold: 5
    #replicas: 1 # Keep this desired state when metrics are unavailable
  triggers:
  - type: aws-sqs-queue
    authenticationRef:
      name: keda-trigger-auth-aws
    metadata:
      queueURL: https://sqs.us-east-1.amazonaws.com/458419607076/MySQSQueue-ForKEDA-Demo
      queueLength: "5"              # batch size
      awsRegion: us-east-1
      