apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: my-app-hpa
  namespace: hpa-demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-app
  minReplicas: 1   # Set the minimum number of replicas
  maxReplicas: 10  # Set the maximum number of replicas
  targetCPUUtilizationPercentage: 30
