apiVersion: v1
kind: Service
metadata:
  name: my-app-svc
  namespace: hpa-demo
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP    
      nodePort: 32000  # Specify the NodePort number
      port: 80
      targetPort: 80
  type: NodePort
  