apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: enforce-deployment-label-replica-count
  namespace: development
spec:
  validationFailureAction: Enforce 
  rules:
    - name: check-for-label
      match:
        resources:
          kinds:            
            - Deployment
      validate:
        message: "You must have the label, team_name for all deployments."
        pattern:
          metadata:
            labels:
              team_name: "?*"

    - name: create-max-two
      match:
        any:
        - resources:
            kinds:
            - Deployment
      validate:
        message: The replica count for this Deployment may not exceed 2.
        pattern:
          spec:
            replicas: <= 2

    # This rule can be used to limit scale operations based upon Deployment labels assuming the given label
    # is also used as a selector.
    # - name: scale-max-3
    #   match:
    #     any:
    #     - resources:
    #         kinds:
    #         - Deployment/scale
    #   validate:
    #     message: The replica count for this Deployment may not exceed 3.
    #     pattern:
    #       (status):
    #         (selector): "*type=monitoring*"
    #       spec:
    #         replicas: <= 3