apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: generate-postgres-configmap
spec:
  rules:
    - name: generate-postgres-configmap
      match:
        resources:
          kinds:
            - Namespace
      preconditions:
        - key: "{{ request.object.metadata.labels.team }}"
          operator: Equals
          value: "infra"
      generate:
        apiVersion: v1
        kind: ConfigMap
        name: postgres-config
        namespace: "{{ request.object.metadata.name }}"
        synchronize: true
        data:
          postgres.conf: |
            # Sample PostgreSQL Configuration
            listen_addresses = '*'
            port = 5432
            max_connections = 100
            shared_buffers = 128MB
            work_mem = 4MB
            maintenance_work_mem = 64MB
            timezone = 'UTC'
            log_statement = 'ddl'
