apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
  namespace: development
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: busybox
          image: busybox
          command: ["echo", "Hello, Welcome to the DevOps Malayalam community! Let's deep dive into Kyverno today."]
