apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: cleanup-completed-jobs
spec:
  rules:
    - name: cleanup-jobs
      match:
        resources:
          kinds:
            - Job
      preconditions:
        all:
          - key: "{{ request.operation }}"
            operator: In
            value: ["DELETE"]
      mutate:
        patchStrategicMerge:
          spec:
            ttlSecondsAfterFinished: 86400 # Clean up after 24 hours
